# Generated by Django 5.0.6 on 2024-05-28 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accidentestransitohmo20122021',
            options={},
        ),
    ]
