# Generated by Django 5.0.6 on 2024-05-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_accidentestransitohmo20122021_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentesHmo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('numero_mes', models.IntegerField()),
                ('mes', models.TextField()),
                ('tipo_accidente', models.TextField()),
                ('estado', models.TextField()),
                ('nombre_municipio', models.TextField()),
                ('total_accidentes', models.IntegerField()),
                ('suma_muertos', models.IntegerField()),
                ('suma_heridos', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='AccidentesTransitoHmo20122021',
        ),
    ]
