# Generated by Django 5.0.6 on 2024-05-28 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_accidenteshmo_delete_accidentestransitohmo20122021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accidenteshmo',
            options={'managed': False},
        ),
    ]
