# Generated by Django 5.0.6 on 2024-05-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_accidenteshmo_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accidenteshmo',
            table='accidentes_transito_hmo_2012_2021',
        ),
    ]
